services:
  # База данных для микросервиса авторизации
  auth-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  # База данных для основного микросервиса
  core-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: core_user
      POSTGRES_PASSWORD: core_password
      POSTGRES_DB: core_db
    ports:
      - "5433:5432"
    volumes:
      - core_db_data:/var/lib/postgresql/data

  # База данных для query микросервиса
  query-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: query_user
      POSTGRES_PASSWORD: query_password
      POSTGRES_DB: query_db
    ports:
      - "5434:5432"
    volumes:
      - query_db_data:/var/lib/postgresql/data

# Kafka
  kafka:
    image: apache/kafka:latest
    container_name: skaldenginebackend-kafka
    user: "0:0"
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://skaldenginebackend-kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: -1
      KAFKA_LOG_RETENTION_BYTES: -1
    volumes:
      - kafka_data:/var/lib/kafka/data

  event-logger:
    build:
      context: ./services/event_logger_service
    container_name: skaldenginebackend-event-logger
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=skaldenginebackend-kafka:29092
      - KAFKA_TOPIC_EVENTS=skaldenginebackend_entity_events
    depends_on:
      - kafka

volumes:
  auth_db_data:
  core_db_data:
  query_db_data:
  kafka_data: # Том для сохранения данных Kafka